alias psql=/Applications/Postgres.app/Contents/MacOS/bin/psql
alias vim=/usr/local/Cellar/macvim/7.3-66/MacVim.app/Contents/MacOS/Vim
alias shutupvim='rm -v ~/tmp/*.sw* /var/tmp/*.sw*'

alias migrate='rake db:migrate && rake db:test:prepare'
alias be='bundle exec'

alias rspec='rspec --color --format documentation'
alias mocha='mocha --require should'

# props to https://twitter.com/kentaro/status/398296840711335936
alias green='echo ""; echo "(•_•)"; echo "<)   )╯ UNIT"; echo " /    \   ";
  echo ""; echo "\(•_•)"; echo " (   (>  TEST"; echo " /    \  "; echo "";
  echo "(•_•) "; echo "<)   )>  PASSED"; echo " /    \ "; echo ""'

alias gitpiv='. ~/code/git-pivotal-hooks/gitpiv-setup.sh'
alias julia='~/code/julia/usr/bin/julia-release-readline'

# virtualenv aliases
# http://blog.doughellmann.com/2010/01/virtualenvwrapper-tips-and-tricks.html
alias v='workon'
alias v.deactivate='deactivate'
alias v.mk='mkvirtualenv --no-site-packages'
alias v.mk_withsitepackages='mkvirtualenv'
alias v.rm='rmvirtualenv'
alias v.switch='workon'
alias v.add2virtualenv='add2virtualenv'
alias v.cdsitepackages='cdsitepackages'
alias v.cd='cdvirtualenv'
alias v.lssitepackages='lssitepackages'
